scala-version: "2.12.14"
name: "parallel_t-SNE"
version: "SNAPSHOT-0.1.0"
filePath: "gs://scala-and-spark-2/resources/mnist2500_X.txt"

sparkConfig:
  appName: "Spark-App"
  master: "yarn-cluster"    # local[*] for local, yarn-cluster for Dataproc
  sparkBindHost: "127.0.0.1"
  sparkBindAddress: "127.0.0.1"

main:
  sampleSize: 1000
  partitions: 200
  perplexity: 30

tSNE:
  k: 2
  max_iter: 20
  initial_momentum: 0.5
  final_momentum: 0.8
  partitions: 2
  lr: 500.0
  minimumgain: 0.01
  export: false
  print: true
  takeSamples: 10
  kNNapprox: false


PCA:
  reduceTo: 50