scala-version: "2.12.14"
name: "parallel_t-SNE"
version: "SNAPSHOT-0.1.0"
dataFile: "mnist2500_X.txt"

sparkConfig:
  appName: "Main"
  master: "yarn" # local[*] for local, spark://localhost:7077 for cluster
  sparkBindHost: "127.0.0.1"
  sparkBindAddress: "127.0.0.1"

main:
  sampleSize: 1000
  partitions: 12
  perplexity: 30

tSNE:
  k: 2
  max_iter: 100
  initial_momentum: 0.5
  final_momentum: 0.8
  partitions: 12
  lr: 500.0
  minimumgain: 0.01
  export: true
  print: true
  takeSamples: 10
  kNNapprox: false


PCA:
  reduceTo: 50