scala-version: "2.12.14"
name: "parallel_t-SNE"
version: "test-run" # Change version name also in build.sbt
dataFileInGs: "/resources/mnist2500_X.txt"
labelFileInGs: "/resources/mnist2500_labels.txt"

shellConfig:
  gcProjectName: "paralleltsne"
  gsBucket: "scala-and-spark"
  clusterName: "t-sne"
  createCluster: false
  deleteCluster: false
  emptyGSBucket: true
  masterMachineType: "n1-standard-4"
  workerMachineType: "n1-standard-4"
  imageVersion: "2.1.2-ubuntu20"

rConfig:
  gsAuthFile: "data/paralleltsne-e66b762160b7.json"


sparkConfig:
  local: false
  appName: "Main"
  master: "local[*]"  #for local, spark://localhost:7077 for cluster
  shufflePartitions: "36"
  defaultParallelism: "36"
  sparkBindHost: "127.0.0.1"
  sparkBindAddress: "127.0.0.1"

main:
  sampleSize: 40
  partitions: 32
  perplexity: 30

tSNE:
  k: 2
  max_iter: 2
  initial_momentum: 0.5
  final_momentum: 0.8
  partitions: 32
  lr: 500.0
  minimumgain: 0.01
  export: true
  print: true
  takeSamples: 40
  kNNapprox: true


PCA:
  reduceTo: 50