scala-version: "2.12.14"
name: "parallel_t-SNE"
version: "SNAPSHOT-0.1.0"
dataFile: "gs://scala-and-spark-2/resources/mnist2500_X.txt"

sparkConfig:
  local: false
  appName: "Main"
  master: "local[*]"  #for local, spark://localhost:7077 for cluster
  shufflePartitions: "36"
  defaultParallelism: "36"
  sparkBindHost: "127.0.0.1"
  sparkBindAddress: "127.0.0.1"

main:
  sampleSize: 40
  partitions: 32
  perplexity: 30

tSNE:
  k: 2
  max_iter: 2
  initial_momentum: 0.5
  final_momentum: 0.8
  partitions: 32
  lr: 500.0
  minimumgain: 0.01
  export: true
  print: true
  takeSamples: 40
  kNNapprox: true


PCA:
  reduceTo: 50