scala-version: "2.12.14"
name: "parallel_t-SNE"
version: "SNAPSHOT-0.1.0"
dataFile: "mnist2500_X.txt"

sparkConfig:
  appName: "Spark-App"
  master: "local[*]"
  sparkBindHost: "127.0.0.1"
  sparkBindAddress: "127.0.0.1"

main:
  sampleSize: 1000
  partitions: 2
  perplexity: 30

tSNE:
  k: 2
  max_iter: 100
  initial_momentum: 0.5
  final_momentum: 0.8
  partitions: 2
  export: false
  lr: 500.0
  minimumgain: 0.01

mlPCA:
  reduceTo: 50