version: "3.3"
services:
  spark-master:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-a:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-a
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
  spark-worker-b:
    image: cluster-apache-spark:3.0.2
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-b
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
  demo-database:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=casa1234

#version: "3.3"
#services:
#  spark-scala-env:
#    image: app/spark-scala-env:latest
#    build:
#      context: .
#      dockerfile: Dockerfile
#  app-spark-scala:
#    image: app/app-spark-scala:latest
#    build:
#      context: .
#      dockerfile: Dockerfile-app
#  spark-master:
#    image: app/app-spark-scala:latest
#    container_name: spark-master
#    hostname: localhost
#    ports:
#      - "8080:8080"
#      - "7077:7077"
#    networks:
#      - spark-network
#    environment:
#      - "SPARK_LOCAL_IP=spark-master"
#      - "SPARK_MASTER_PORT=7077"
#      - "SPARK_MASTER_WEBUI_PORT=8080"
#    command: ["sh", "-c", "/spark/bin/spark-class org.apache.spark.deploy.master.Master --ip $${SPARK_LOCAL_IP} --port $${SPARK_MASTER_PORT} --webui-port $${SPARK_MASTER_WEBUI_PORT}"]
#  spark-worker:
#    image: app/app-spark-scala:latest
#    hostname: localhost
#    depends_on:
#      - spark-master
#    ports:
#      - 8080
#    networks:
#      - spark-network
#    #network_mode: host
#    environment:
#      - "SPARK_MASTER=spark://spark-master:7077"
#      - "SPARK_WORKER_WEBUI_PORT=8080"
#      - "SPARK_WORKER_CORES=2"
#    command: ["sh", "-c", "/spark/bin/spark-class org.apache.spark.deploy.worker.Worker --webui-port $${SPARK_WORKER_WEBUI_PORT} $${SPARK_MASTER}"]
#  app-submit-job:
#    image: app/app-spark-scala:latest
#    ports:
#      - "4040:4040"
#    environment:
#      - "SPARK_APPLICATION_MAIN_CLASS=com.app.spark.TestAssembly"
#      - "SPARK_MASTER=spark://spark-master:7077"
#      - "APP_PACKAGES=org.apache.spark:spark-sql-kafka-0-10_2.12:3.0.0-preview2"
#      - "APP_JAR_LOC=/app/target/scala-2.12/app_spark_scala-assembly-0.2.jar"
#    hostname: localhost
#    networks:
#      - spark-network
#    volumes:
#      - ./appdata:/appdata
#    command: ["sh", "-c", "/spark/bin/spark-submit --packages $${APP_PACKAGES} --class $${SPARK_APPLICATION_MAIN_CLASS} --master $${SPARK_MASTER} $${APP_JAR_LOC}"]
#networks:
#  spark-network:
#    driver: bridge
#    ipam:
#      driver: default